config/routes.rb
require 'api_constraints'
Rails.application.routes.draw do

  namespace :api, defaults: {format: 'json'} do
    scope module: :v1, constraints: ApiConstraints.new(version: 1, default: true) do
      get '/mobiles/:id', to: 'mobiles#index'
      post '/mobiles/new_order', to: 'mobiles#new_order'
      post '/mobiles/request_account', to: 'mobiles#request_account'
      
      get '/restaurants/index/:id', to: 'restaurants#index'
      get '/restaurants/orders/:table_id', to: 'restaurants#orders'
      post '/restaurants/update_product', to: 'restaurants#update_product'
      post '/restaurants/update_order', to: 'restaurants#update_order'
    end
  end

  resources :restaurants, :tables, :products, :categories

  get 'tables/new/:restaurant_id', to: "tables#new"
  get 'tables/index/:restaurant_id', to: "tables#index"

  get '/', to: "orders#index2"
  
  post 'restaurants/add_c', to: "restaurants#add_categories"
  post 'restaurants/add_p', to: "restaurants#add_products"

end

app/controllers/tables_controller.rb
class TablesController < ApplicationController
  

  def index
    @tables = Table.where(restaurant_id: params[:restaurant_id])

  end

  def show
    require 'rqrcode_png'
    @table = Table.find(params[:id])

    @qr = RQRCode::QRCode.new(@table.id.to_s).to_img.resize(200, 200).to_data_url
  end

  def new
  	@restaurant = Restaurant.find(params[:restaurant_id])
    
    @table = Table.new
    @tables = @restaurant.tables 
  end

  def create
  	@table = Table.create(table_params)
    @table.qr = @table.id
		if @table.save
			flash[:success] = 'Mesa registrada.'
			redirect_to :back
    else
		  render 'new'
		end
  end

  def destroy
    table = Table.find(params[:id])
    table.destroy
    flash[:success] = 'Mesa eliminada.'
    redirect_to :back
  end

  private
  def table_params
    params.require(:table).permit(:name, :capacity, :restaurant_id)
  end
  
end

app/helpers/tables_helper.rb
module TablesHelper
end

app/views/tables/_form.html.erb
<%= form_for @table, url: {action: "create"}, html: {class: 'form-inline col-xs-9 center'} do |f| %>
	<input type="hidden" name="table[restaurant_id]" id="table_restaurant_id" value=<%= @restaurant.id%> >
	<div class="form-group">
	  <%=f.text_field :name, class: 'form-control', placeholder: 'Nombre' %>
	</div>
	<div class="form-group">
	  <%=f.text_field :capacity, class: 'form-control', placeholder: 'Capacidad' %>
	</div>

  <%= f.submit "Registrar", :name => nil, class: "btn btn-primary" %>
<% end %>

app/views/tables/edit.html.erb
<h1>Tables#edit</h1>
<p>Find me in app/views/tables/edit.html.erb</p>

app/views/tables/index.html.erb
<%#= javascript_include_tag 'orders', 'data-turbolinks-track' => true %>
<%= javascript_include_tag "orders"%>
<h1>Mesas</h1>

<% @tables.each do |t| %>
<div class="col-xs-6">
	<div class="panel panel-info">
		<div class="panel-heading"><%= t.name %> [<%= t.capacity %>] </div>

		<div class="panel-body">
	    <div class="col-xs-3">

	    </div>
	    <div class="col-xs-9" ng-controller="OrdersController as order">
	    	<table class="table">
	    		<thead>
	    			<tr>
	    				<td>Producto</td>
							<td>Precio unitario</td>
							<td>Cantidad</td>
							<td>Total</td>
	    			</tr>
	    		</thead>
	    		<tbody>
		    		<% total = 0 %>
			    	<% t.orders.each do |o| %>
			    		<% o.orders_products.each do |op| %>
				    		<tr>
				    			<td><%=op.product.name%></td>
				    			<td><%=number_to_currency(op.product.price, precision: 0) %></td>
				    			<td><%=op.qty%>
				    			<td><%=number_to_currency( op.qty*op.product.price, precision: 0)%></td>
				    		</tr>
			    			<% total +=  op.qty*op.product.price %>	
			    		<% end %>
			    	<% end %>
				    	<tr>
				    		<td colspan="4"><%= number_to_currency(total,precision: 0) %></td>
				    	</tr>
		    	</tbody>
		    </table>
	    </div>
	  </div>
	</div>
</div>
<% end %>

app/views/tables/new.html.erb
<div class="panel panel-default">
  <div class="panel-heading">
    Nueva Mesa :: <%= @restaurant.name %>
    <%#= link_to "Listado", restaurants_path, class: "label label-default" %>
  </div>
  <div class="panel-body">
    <%= render 'form' %>
  </div>
  <table class="table">
		<thead>
			<tr>
				<td>#Mesa</td>
				<td>Capacidad</td>
				<td>Acciones</td>
			</tr>
		</thead>
		<tbody>
			<% @tables.each do |t| %>
				<tr>
					<td><%= t.name%></td>
					<td><%= t.capacity%></td>
					<td>
						<%= link_to "QR", t, class: "label label-info" %>
						<%= link_to "Eliminar", table_path(t), class: "label label-danger", method: :delete, data: { confirm: '¿Seguro desea eliminar la mesa '+t.name+'?' } %>
					</td>
				</tr>
			<% end %>
		</tbody>
	</table>
</div>

app/views/tables/show.html.erb
<div class="panel panel-default">
  <div class="panel-heading">
    QR >> <%= @table.name %> :: <%= @table.restaurant.name %>
    <%#= link_to "Listado", restaurants_path, class: "label label-default" %>
  </div>
  <div class="panel-body">
    <%= image_tag @qr %>
  </div>
</div>