config/routes.rb
require 'api_constraints'
Rails.application.routes.draw do

  namespace :api, defaults: {format: 'json'} do
    scope module: :v1, constraints: ApiConstraints.new(version: 1, default: true) do
      get '/mobiles/:id', to: 'mobiles#index'
      post '/mobiles/new_order', to: 'mobiles#new_order'
      post '/mobiles/request_account', to: 'mobiles#request_account'
      
      get '/restaurants/index/:id', to: 'restaurants#index'
      get '/restaurants/orders/:table_id', to: 'restaurants#orders'
      post '/restaurants/update_product', to: 'restaurants#update_product'
      post '/restaurants/update_order', to: 'restaurants#update_order'
    end
  end

  resources :restaurants, :tables, :products, :categories

  get 'tables/new/:restaurant_id', to: "tables#new"
  get 'tables/index/:restaurant_id', to: "tables#index"

  get '/', to: "orders#index2"
  
  post 'restaurants/add_c', to: "restaurants#add_categories"
  post 'restaurants/add_p', to: "restaurants#add_products"

end

app/models/restaurant.rb
class Restaurant < ActiveRecord::Base
	has_many :categories
	has_many :products
	has_many :tables
	has_many :menus
	has_many :orders

	def self.search(search, page)
		#joins(:type).order('restaurants.name').where('restaurants.name LIKE ?', "%#{search}%").paginate(page: page, per_page: 5)
		order('restaurants.name').where('restaurants.name LIKE ?', "%#{search}%").paginate(page: page, per_page: 5)
		#order('name').paginate(page: page, per_page: 5)
	end

	def tables
		Table.where(:restaurant_id => self.id)
	end


end

app/controllers/api/v1/restaurants_controller.rb
module Api
  module V1
    class RestaurantsController < ApplicationController
      skip_before_filter :verify_authenticity_token  
      #before_filter :set_headers

      respond_to :json

      #Listado de mesas por restaurant: para mesas
      def index
        restaurant = Restaurant.where(:id => params[:id])
        respond_with restaurant[0].to_json(:include =>{ :tables => {:methods => [:orders]}})
      end

      #Listado de ordenes por mesa: para detalle de mesa
      def orders
        orders = Order.where(:table_id => params[:table_id], :status => ["Solicitada","En proceso","Despachada","Cuenta"])
        orders = orders.to_json( 
          :methods => [ :restaurant, :table ], 
          :include => { :orders_products => { :include => :product } }
        )
        respond_with orders
      end

      #Actualizacion del estado de la orden
      def update_order
        data = params[:order]
        
        order = Order.find(data[:id])
        total = 0
        order.update_attributes(:status => data[:status])
        data[:orders_products].each_with_index do |op, index|
          order_product = OrdersProduct.find(op[:id])
          
          case op['status']
            when "Solicitada"
              prod = Product.find(order_product['product_id'])
              total = total + prod.price*op['qty']   
            when "Aprobado"
              prod = Product.find(order_product['product_id'])
              total = total + prod.price*op['qty'] 
          end

          order_product.update_attributes(:status=>op[:status])
        end
        order.update_attributes(:total => total)

        render :json => {:order => order, :result => "ACK"}
      end
    end
  end
end

app/controllers/restaurants_controller.rb
class RestaurantsController < ApplicationController

  def index
    @restaurants = Restaurant.search(params[:search], params[:page])
  end

  def new
    @restaurant = Restaurant.new
  end

  def show
    @restaurant = Restaurant.find(params[:id])
    @category = Category.new
    @product = Product.new

    @categories = Category.where(restaurant_id: @restaurant.id).order(:order)
    @products = Product.where(restaurant_id: @restaurant.id).order(:order)
    #@menus = Menu.getMenusByRestaurant(params[:id])
  end

  def edit
    @restaurant = Restaurant.find(params[:id])
  end

  def update
    @restaurant = Restaurant.find(params[:id])
 
    if @restaurant.update(restaurant_params)
      redirect_to @restaurant
    else
      render 'edit'
    end
  end

  def create
    @restaurant = Restaurant.create(restaurant_params)
    #redirect_to restaurant_path(@restaurant)
    respond_to do |format|
      if @restaurant.save
        #redirect_to @restaurant
        flash[:success] = 'Restaurant registrado.'
        format.html { redirect_to @restaurant }
      else
        render 'new'
      end
    end
  end

  def destroy
    @restaurant = Restaurant.find(params[:id])
    @restaurant.destroy
    respond_to do |format|
      flash[:success] = 'Restaurant eliminado.'
      format.html { redirect_to restaurants_url }
    end
  end

  def add_categories
    category = Category.create(category_params)
    @restaurant = Restaurant.find(category.restaurant_id)
    #redirect_to restaurant_path(@restaurant)
    if category.save
      #redirect_to @restaurant
      flash[:success] = 'Categoria guardada.'
      redirect_to @restaurant 
    else
      render 'new'
    end
  end

  def add_products
    product = Product.create(product_params)
    @restaurant = Restaurant.find(product.restaurant_id)

    if product.save
      flash[:success] = 'Producto guardado.'
      redirect_to @restaurant
    else
      render 'new'
    end
  end


  private
  def restaurant_params
    params.require(:restaurant).permit(:name, :code, :address, :type_id)
  end
  def category_params
    params.require(:category).permit(:name, :image, :order, :restaurant_id)
  end
  def product_params
    params.require(:product).permit(:name, :price, :image, :sku, :category_id, :order, :restaurant_id)
  end
end

app/views/restaurants/_form.html.erb
<%= form_for @restaurant, url: {action: "create"}, html: {class: 'col-xs-9 center'} do |f| %>

<div class="form-group">
  <label for="exampleInputEmail1">Nombre</label>
  <%=f.text_field :name, class: 'form-control', placeholder: 'Nombre' %>
</div>

  <%= f.submit "Registrar", :name => nil, class: "btn btn-primary" %>
<% end %>

app/views/restaurants/create.html.erb
<h1>Restaurants#create</h1>
<p>Find me in app/views/restaurants/create.html.erb</p>

app/views/restaurants/edit.html.erb
<div class="panel panel-default">
  <div class="panel-heading">
    <%= @restaurant.name %>
    <%= link_to "Listado", restaurants_path, class: "label label-default" %>
  </div>
  <div class="panel-body">
    <%= render 'form' %>
  </div>
</div>

app/views/restaurants/index.html.erb
<div class="panel panel-default">
	<div class="panel-heading">
		Restaurants
		<%#= link_to "Nuevo", new_restaurant_path, class: "label label-default" %>
	</div>
	<div class="col-lg-6"></div>
	<div class="panel-body col-lg-6">
		<%= form_tag restaurants_path, :method=>'get' do %>
			<div class="input-group">
				<%=text_field_tag :search, params[:search], class: 'form-control', placeholder: 'Nombre' %>
				<span class="input-group-btn">
				<%=submit_tag "Buscar", :name => nil, class: "btn btn-primary" %>
				</span>
			</div>
		<% end %>
	</div>
	<table class="table table-responsive table-striped">
		<thead>
			<tr>
				<th>Nombre</th>
				<th>Tipo cocina</th>
				<th>Dirección</th>
				<th>Acciones</th>
			</tr>
		</thead>
		<tbody>
		<% @restaurants.each do |r| %>
			<tr>
				<td><%= r.name %></td>
				<td><%#= r.type.name %></td>
				<td><%#= r.address%></td>
				<td>
					<%= link_to "Menú", restaurant_path(r), class: "label label-info" %>
					<%= link_to "Mesas", new_table_path(restaurant_id: r.id), class: "label label-success" %>
					<%= link_to "Pedidos", tables_path(restaurant_id: r.id), class: "label label-success" %>
					<!--<%= link_to "Editar", edit_restaurant_path(r), class: "label label-info" %>-->
					<%= link_to "Eliminar", restaurant_path(r), class: "label label-danger", method: :delete, data: { confirm: '¿Seguro desea eliminar el restaurant '+r.name+'?' } %>
				</td>
			</tr>
		<% end %>
		</tbody>
	</table>
	<%= will_paginate @restaurants %>
</div>

app/views/restaurants/new.html.erb
<div class="panel panel-default">
  <div class="panel-heading">
    Nuevo Restaurant
    <%#= link_to "Listado", restaurants_path, class: "label label-default" %>
  </div>
  <div class="panel-body">
    <%= render 'form' %>
  </div>
</div>

app/views/restaurants/show.html.erb
<div class="panel panel-default">
	<div class="panel-heading">
		<%= @restaurant.name %>
	</div>
	<div class="panel-body">
	<div class="row">

		<div class="col-sm-6 col-md-6">
		    <div class="thumbnail">
		      <div class="caption">
		        <h3>Categorías</h3>
		        <p>Ingresa las categorías que maneja tu restaurant y asocialos a tus productos</p>
		        <p>
		        	<%= form_for @category, url: {action: "add_categories"}, html: {multipart: true, class: 'form'} do |f| %>
		        	<input type="hidden" name="category[restaurant_id]" id="category_restaurant_id" value=<%= @restaurant.id%> >
		        	<%#= f.text_hidden :restaurant_id value: resta%>
		        	<div class="form-group col-xs-6">
							  <%=f.text_field :name, class: 'form-control', placeholder: 'Nombre categoría' %>
							</div>
							
							<div class="form-group col-xs-6">
							  <%=f.file_field :image, class: 'form-control' %>
							</div>
							<div class="form-group col-xs-2">
							  <%=f.text_field :order, class: 'form-control', placeholder: 'Orden' %>
							</div>
							<div class="form-group col-xs-12">
								<label>
								<%= f.check_box :active %>
								Activo
								</label>
							</div>
							<div class="form-group col-xs-12">
		        		<%= f.submit "Guardar", :name => nil, class: "btn btn-primary" %>
		        	</div>

		        	<% end %>
					<%#= link_to "Categorías", new_restaurant_category_path(@restaurant.code), class: "btn btn-default" %>	
		        </p>
		        <p>
		        	<table class="table">
		        	<% @categories.each do |c| %>
						<tr>
							<td><%= c.name %></td>
							<td><%= c.order %></td>
							<td><%= link_to "Eliminar", category_path(c), class: "label label-danger", method: :delete, data: { confirm: '¿Seguro desea eliminar la categoria '+c.name+'?' } %></td>
						</tr>
		        	<% end %>
		        	</table>
		        </p>
		      </div>
		    </div>
	    </div>
		
		<div class="col-sm-6 col-md-6">
			<div class="thumbnail">
		      <div class="caption">
		        <h3>Productos</h3>
		        <p>Ingresa los productos y asocialos a las categorías</p>
		        <p>
		        	<%= form_for @product, url: {action: "add_products"}, html: {multipart: true, class: 'form'} do |f| %>
		        	<input type="hidden" name="product[restaurant_id]" id="product_restaurant_id" value=<%= @restaurant.id%> >
							<div class="form-group col-xs-6">
							  <%=f.text_field :name, class: 'form-control', placeholder: 'Nombre' %>
							</div>
							<div class="form-group col-xs-6">
							  <%=f.text_field :price, class: 'form-control', placeholder: 'Precio' %>
							</div>
							<div class="form-group col-xs-6">
							  <%=f.text_field :sku, class: 'form-control', placeholder: 'SKU' %>
							</div>
							<div class="form-group col-xs-6">
							  <%=f.collection_select(:category_id, Category.where(restaurant_id: @restaurant.id), :id, :name, {},{:class => 'form-control'}) %>
							</div>
							<div class="form-group col-xs-2">
							  <%=f.text_field :order, class: 'form-control', placeholder: 'Orden' %>
							</div>
							<div class="form-group col-xs-2">
							  <%=f.text_field :qty, class: 'form-control', placeholder: 'Cant.' %>
							</div>
							<div class="form-group col-xs-2">
							  <%=f.text_field :unit, class: 'form-control', placeholder: 'Unidad' %>
							</div>
							<div class="form-group col-xs-6">
							  <%=f.file_field :image, class: 'form-control' %>
							</div>
							
							<div class="form-group col-xs-12">
		        		<%= f.submit "Guardar", :name => nil, class: "btn btn-primary" %>
		        	</div>
		        	<% end %>
					<%#= link_to "Productos", new_product_path, class: "btn btn-default" %>	
		        </p>
		        <p>
		        	<table class="table">
		        	<% @products.each do |p| %>
						<tr>
							<td><%= p.name %></td>
							<td><%= p.category.name %></td>
							<td><%= number_to_currency(p.price,precision: 0) %></td>
							<td><%= link_to "Eliminar", product_path(p), class: "label label-danger", method: :delete, data: { confirm: '¿Seguro desea eliminar el producto '+p.name+'?' } %></td>
						</tr>
		        	<% end %>
		        	</table>
		        </p>
		      </div>
		    </div>
	    </div>

	</div>
	</div>
</div>